### ISSUE TITLE
Travis CI 연동하기

### ISSUE THREAD

**Issue by gyureal** [gyureal/makeAloneSpringAws#11]
## `Jenkins` vs `Travis CI` vs `Code Build(AWS)`
CI에 주로 사용되는 세가지 도구의 특징을 비교해 보았습니다.
- Jenkins
   - 가장 범용적으로 사용됨
   - 설치형이기 때문에 Jenkins를 위한 EC2가 따로 필요함 (금전적 부담)
- Travis CI
   - 깃허브에서 제공하는 무료 CI 서비스
   - 추가적인 비용이 들지 않음
- Code Build(AWS)
   - 빌드 시간만큼 요금이 부과되는 구조 (금전적 부담)     

## Travis CI 
- 주소: https://www.travis-ci.com/
- git 계정으로 연동
- repo 설정
<img width="731" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/9769505f-4781-4a53-9e52-06ef34c8bf8f">

상세 설정은 해당 레포지토리에 .travis.yml 로 해야함
[tutorial](https://docs.travis-ci.com/user/tutorial/)

<img width="535" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/23a292b8-af0f-4f0c-9a79-e303043554d9">

## travis.yml
```yml
language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람 test
notifications:
  email:
    recipients:
      - yonggyu.jeong10@gmail.com


```

<img width="1053" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/76dd51f4-e12a-466c-a511-c8cc66369f84">

## trouble shooting
- 테스트 시, 실패가 나면 test 용 application.yml 파일을 생성했나 확인해 봅니다.
<img width="212" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/3a67f4db-6273-4bdd-8a51-23185d6797e1">

test용 `applicaion.yml` 에는 `application-oauth.yml` 의 부재로 어플리케이션 실행이 실패하는 것을 방지하기 위해 임시 설정이 들어가 있습니다.

<img width="276" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/aae5f3df-3e1b-4bf3-bb55-8692c4f332f4">
