### ISSUE TITLE
빌드 후 파일을 S3에 저장하기

### ISSUE THREAD

**Issue by gyureal** [gyureal/makeAloneSpringAws#12]
## Travis CI -> S3 -> Code Deploy 구조인 이유
> Code Deploy는 파일을 저장하는 기능이 없으며, 빌드 후 빌드된 파일을 저장해 두는 것이 좋기에 S3를 `빌드된 파일 저장소`로 사용합니다.
- `Code Deploy`도 빌드 기능을 제공하지만, 빌드와 배포는 분리되어 있는 것이 좋습니다.

## 단계
- IAM 생성
- Travis CI에 키 등록
- Travis CI와 S3 연동하기

1. IAM 생성하기
- 권한 : `s3FullAccess`, `CodeDeployFullAccess`
<img width="897" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/d2cf9fb6-9f5a-4249-baa7-5702416f9c7c">
- Name 태그

2. Travis CI에 키 등록
> Environment Variables 에 등록된 값들은 .travis.yml 에서 $변수명 으로 사용할 수 있습니다.
<img width="762" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/be388194-acf9-44b9-bd24-98cfc01b6443">

3. S3 생성
- IAM key 로 체크하더라도, public 접근은 막아두는 것이 좋습니다.

4. .travis.yml 추가
```yml
before_deploy:
  - zip -r makeAloneSpringAws *
  - mkdir -p deploy   # travis ci 실행중인 위치에 폴더를 생성합니다.
  - mv makeAloneSpringAws.zip deploy/makeAloneSpringAws.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: my-neighbor-solver # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      branch: main # main branch 허용
```

5. 빌드성공 후 S3 확인
<img width="916" alt="image" src="https://github.com/gyureal/makeAloneSpringAws/assets/78974381/2beec7c4-3582-4f76-b94e-60e9ab58523b">

### trouble shooting
- Skipping a deployment with the s3 provider because this branch is not permitted: main
   - `on: branch: main` 옵션을 추가해준다.
